---
- name: Install the latest version of consul
  yum:
    name: consul
    state: latest

- name: Restart Consul
  ansible.builtin.systemd:
    name: consul.service
    state: restarted
    enabled: yes
