---
# - name: Install the latest version of consul
#   yum:
#     name: consul
#     state: latest

# - name: Restart Consul
#   ansible.builtin.systemd:
#     name: consul.service
#     state: restarted
#     enabled: yes

- name: Remove file (delete file)
  ansible.builtin.file:
    path: /etc/consul.d/jmx_exporter.json
    state: absent

- name: Make sure a service unit is running
  ansible.builtin.systemd:
    state: restarted
    name: consul.service

